# Ansible Galaxy Requirements
# Install with: ansible-galaxy role install -r requirements.yml

roles:
# Docker installation and configuration
- name: geerlingguy.docker
  version: 7.4.1

# Example: MySQL installation
# - name: geerlingguy.mysql
#   version: 4.3.5

# Example: Nginx installation (if using Galaxy instead of custom role)
# - name: geerlingguy.nginx
#   version: 3.1.6
